### PR TITLE
Save state atexit

### PR DESCRIPTION
**Pull request by zcutlip**
Register an `atexit` handler so state gets saved on program termination.

This allows `State` to be used in forms other than:
```
with State() as s:
    do_stuff()
```
Without this, state wasn't always getting saved

### CODE REVIEW

**Comment by richo** [comment]
Is this ever invoked inside the debugger? Or only in Views?

I might just be fearmongering but I think I remember some pretty horrible stuff happening with atexit inside the debuggers. (Probably gdb because lol gdb)

**Comment by zcutlip** [comment]
> Is this ever invoked inside the debugger? Or only in Views?
> 
> I might just be fearmongering but I think I remember some pretty horrible stuff happening with atexit inside the debuggers. (Probably gdb because lol gdb)

Don't know. Should I back it out? Is there a better way?

**Comment by richo** [comment]
I'm not saying to back it out, like I said this is just kinda a memory I have. I feel like I tried to solve some problems with atexit and the result wasn't great, but if this works then awesome!

I will fool around with it a bit and see if anything breaks, if it's only used in views then it's for sure 100% safe anyway.

**Comment by zcutlip** [comment]
Cool, thanks! I'll stay tuned.

**Pull request merged**
